<?php

declare(strict_types=1);

namespace lindemannrock\reportmanager\tests;

use Craft;
use lindemannrock\base\testing\IntegrationTestCase;
use lindemannrock\reportmanager\models\Settings;
use lindemannrock\reportmanager\records\ExportRecord;
use lindemannrock\reportmanager\ReportManager;
use lindemannrock\reportmanager\services\ExportService;
use lindemannrock\reportmanager\services\QueuedExportProvidersService;
use lindemannrock\reportmanager\services\ReportsService;
use lindemannrock\reportmanager\tests\Stubs\StubQueuedExportProvider;

/**
 * Base test case for report-manager integration tests.
 *
 * Layers plugin-specific shorthand on top of {@see IntegrationTestCase}:
 *  - direct accessors for the `exports` / `queuedExportProviders` / `reports`
 *    services
 *  - a marker prefix that rides through both the export record's `dataSource`
 *    column AND every generated file's filename — one prefix cleans both
 *  - {@see installStubProviderService()} for tests that need a queued export
 *    provider registry isolated from anything other plugins may have wired in
 *    via the EVENT_REGISTER_QUEUED_EXPORT_PROVIDERS event
 *  - {@see cleanupExternalState()} override that purges marker-tagged files
 *    from the local export storage directory between tests
 *
 * @since 5.4.0
 */
abstract class TestCase extends IntegrationTestCase
{
    /**
     * Marker prefix used for every test-seeded row + generated file.
     *
     * Picked so `purgeRowsByMarker`'s LIKE wildcard handling won't trip on
     * unintended regex characters, and so the same prefix can be used as a
     * file-glob pattern in {@see cleanupExternalState()}. Plain ASCII +
     * underscores only.
     */
    protected const MARKER = '__rm_test_';

    protected ExportService $exports;

    protected QueuedExportProvidersService $queuedExportProviders;

    protected ReportsService $reports;

    protected function setUp(): void
    {
        parent::setUp();
        $plugin = ReportManager::$plugin;
        $this->exports = $plugin->exports;
        $this->queuedExportProviders = $plugin->queuedExportProviders;
        $this->reports = $plugin->reports;
        $this->purgeTestRows();
    }

    protected function tearDown(): void
    {
        $this->purgeTestRows();
        parent::tearDown();
    }

    /**
     * Plugin settings shorthand.
     */
    protected function settings(): Settings
    {
        /** @var Settings $settings */
        $settings = ReportManager::$plugin->getSettings();
        return $settings;
    }

    /**
     * Swap the cached {@see QueuedExportProvidersService} for a fresh instance
     * with the {@see StubQueuedExportProvider} registered via the standard
     * EVENT_REGISTER_QUEUED_EXPORT_PROVIDERS event. The service caches the
     * registered-providers list on first access, so a wholesale component
     * swap is the only reliable way to seed a known registry across tests.
     */
    protected function installStubProviderService(): StubQueuedExportProvider
    {
        StubQueuedExportProvider::reset();

        $service = new QueuedExportProvidersService();
        $service->on(
            QueuedExportProvidersService::EVENT_REGISTER_QUEUED_EXPORT_PROVIDERS,
            static function ($event): void {
                $event->providers[StubQueuedExportProvider::handle()] = [
                    'handle' => StubQueuedExportProvider::handle(),
                    'name' => StubQueuedExportProvider::displayName(),
                    'class' => StubQueuedExportProvider::class,
                ];
            }
        );

        $this->swapPluginComponent('report-manager', 'queuedExportProviders', $service);
        $this->queuedExportProviders = $service;
        $this->exports = ReportManager::$plugin->exports;

        return new StubQueuedExportProvider();
    }

    /**
     * Drain marker-tagged export rows. The `dataSource` column on
     * `{{%reportmanager_exports}}` mirrors `providerHandle` for queued exports,
     * so a marker-prefixed handle lands here, and an idle `LIKE` purge by that
     * prefix is enough to drain every test-owned row regardless of status.
     */
    protected function purgeTestRows(): void
    {
        $this->purgeRowsByMarker(ExportRecord::tableName(), 'dataSource', self::MARKER);
    }

    /**
     * Remove marker-tagged generated files from the local export directory.
     *
     * The export base path is whatever {@see Settings::getExportPath()}
     * resolved at boot — typically `@storage/report-manager/exports/`. Files
     * generated by the queued-export pipeline get filenames starting with the
     * provider handle, but `ExportService::ensureFilenameExtension()` runs
     * `trim($filename, '.-_')` before persisting, which strips the leading
     * underscores off the marker. The matching glob therefore looks for
     * `rm_test_*` (post-trim form) rather than `__rm_test_*` (DB-column form).
     * CP-generated exports never share either prefix.
     */
    protected function cleanupExternalState(): void
    {
        $basePath = $this->exports->getExportBasePath();

        if ($this->exports->isUsingVolume()) {
            return;
        }

        if (!is_dir($basePath)) {
            return;
        }

        $pattern = rtrim($basePath, '/') . '/rm_test_*';

        foreach (glob($pattern) ?: [] as $file) {
            if (is_file($file)) {
                @unlink($file);
            }
        }
    }
}
